name: Workflow Secret
on: push
jobs:
  display_value:
    runs-on: ubuntu-latest
    outputs:
      mon_retour: ${{steps.step_return.outputs.result}}
    steps:
      - run: |
          echo "${{ secrets.DATABASE_PASSWORD }}"
          echo "${{ vars.VERSION }}"
      - name: Github Script
        uses: actions/github-script@v7.0.1
        id: step_return
        with:
          script: return "Mon retour";
  get_return:
    runs-on: ubuntu-latest
    needs: display_value
    steps:
      - run: echo ${{needs.display_value.outputs.mon_retour}}

